<xsl:stylesheet version="2.0"
                xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:tmdd="http://www.tmdd.org/3/messages"
                xmlns:tlc="http://tlc.cdm.charm.cgi.com"
                xmlns:xls="http://www.w3.org/1999/XSL/Transform"
                xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                exclude-result-prefixes="#all">

    <xsl:template match="tlc:tlc_publish">
        <generic-status-item>
            <device-status-header xsi:type="tmdd:DeviceStatusHeaderCharm">
                <organization-information>
                    <organization-id>RWS</organization-id>
                </organization-information>
                <device-id>
                    <xsl:value-of select="tlc:tlc_id/tlc:id"/>
                </device-id>
                <device-status>on</device-status>
                <xsl:if test="tlc:tlc_inventory_attr/tlc:tlc_generic_attr">
                <device-type>
                    <xls:value-of
                            select="tlc:tlc_inventory_attr/tlc:tlc_generic_attr/tlc:tlc_type"/>
                </device-type>
                </xsl:if>
            </device-status-header>
            <xsl:if test="tlc:tlc_status_attr != ''">
            <generic-device-list>
                <xsl:if test="tlc:tlc_inventory_attr/tlc:tlc_generic_attr">
                    <generic-object>
                        <object-name>VRIID</object-name>
                        <generic-element-list>
                            <generic-element>
                                <element-name>1</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_inventory_attr/tlc:tlc_generic_attr/tlc:intersection_number"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>2</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_inventory_attr/tlc:tlc_generic_attr/tlc:intersection_description"/>
                                </element-value>
                            </generic-element>
                        </generic-element-list>
                    </generic-object>
                    <generic-object>
                        <object-name>KTIJD</object-name>
                        <generic-element-list>
                            <generic-element>
                                <element-name>0</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_inventory_attr/tlc:tlc_generic_attr/tlc:date_time"/>
                                </element-value>
                            </generic-element>
                        </generic-element-list>
                    </generic-object>
                    <generic-object>
                        <object-name>TID</object-name>
                        <generic-element-list>
                            <generic-element>
                                <element-name>0</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_inventory_attr/tlc:tlc_generic_attr/tlc:ivera_version"/>
                                </element-value>
                            </generic-element>
                        </generic-element-list>
                    </generic-object>
                    <generic-object>
                        <object-name>YID</object-name>
                        <generic-element-list>
                            <generic-element>
                                <element-name>0</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_inventory_attr/tlc:tlc_generic_attr/tlc:application_id"/>
                                </element-value>
                            </generic-element>
                        </generic-element-list>
                    </generic-object>
                </xsl:if>
                <xsl:if test="tlc:tlc_status_attr">
                    <generic-object>
                        <object-name>VRISTAT</object-name>
                        <generic-element-list>
                            <generic-element>
                                <element-name>0</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_akt"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>1</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_bd"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>2</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_cen"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>3</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_appl"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>4</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_klok"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>5</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_process"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>6</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:status_info/tlc:current_status_bewaker"/>
                                </element-value>
                            </generic-element>
                        </generic-element-list>
                    </generic-object>
                    <generic-object>
                        <object-name>VRIFSUB</object-name>
                        <generic-element-list>
                            <generic-element>
                                <element-name>0</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:error_status/tlc:detection"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>1</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:error_status/tlc:lamps"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>2</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:error_status/tlc:application"/>
                                </element-value>
                            </generic-element>
                            <generic-element>
                                <element-name>3</element-name>
                                <element-value>
                                    <xsl:value-of
                                            select="tlc:tlc_status_attr/tlc:error_status/tlc:public_transportation"/>
                                </element-value>
                            </generic-element>
                        </generic-element-list>
                    </generic-object>
                    <xsl:if test="tlc:tlc_status_attr/tlc:ivera_status">
                        <generic-object>
                            <object-name>BB0</object-name>
                            <generic-element-list>
                                <generic-element>
                                    <element-name>0</element-name>
                                    <element-value>
                                        <xsl:value-of
                                                select="tlc:tlc_status_attr/tlc:ivera_status/tlc:supported_objects/tlc:bb0"/>
                                    </element-value>
                                </generic-element>
                            </generic-element-list>
                        </generic-object>
                        <generic-object>
                            <object-name>BB1</object-name>
                            <generic-element-list>
                                <generic-element>
                                    <element-name>1</element-name>
                                    <element-value>
                                        <xsl:value-of
                                                select="tlc:tlc_status_attr/tlc:ivera_status/tlc:supported_objects/tlc:bb1"/>
                                    </element-value>
                                </generic-element>
                            </generic-element-list>
                        </generic-object>
                        <xsl:for-each
                                select="tlc:tlc_status_attr/tlc:ivera_status/tlc:ivera_object">
                            <generic-object>
                                <object-name>
                                    <xsl:value-of select="tlc:name"/>
                                </object-name>
                                <display-name>
                                    <xsl:value-of select="tlc:displayname"/>
                                </display-name>
                                <generic-element-list>
                                    <xsl:for-each
                                            select="tlc:parameters/tlc:parameter">
                                        <generic-element>
                                            <element-name>
                                                <xsl:value-of select="tlc:key"/>
                                            </element-name>
                                            <element-value>
                                                <xsl:value-of
                                                        select="tlc:value"/>
                                            </element-value>
                                        </generic-element>
                                    </xsl:for-each>
                                </generic-element-list>
                            </generic-object>
                        </xsl:for-each>
                    </xsl:if>
                </xsl:if>
            </generic-device-list>
            </xsl:if>
        </generic-status-item>
    </xsl:template>
</xsl:stylesheet>